### ISSUE TITLE
Provide a dedicated REST route for summarizing exam marking

### ISSUE THREAD

**Issue by arnobl** [correctexam/corrigeExamBack#28]
To end the PR https://github.com/correctexam/corrigeExamFront/pull/28/ (provide users with a summary page related to the marking of a given exam).
I need a dedicated REST route (eg `api/summaryexam/{examId}`) that provide the data following this format:

```json
{
  "nameExam": "foo",
  "questions": [{
      "id": 1,
      "answeredSheets": 2,
      "firstUnmarkedSheet": 10
  }],
  "students": [{
    "id": 23,
    "answeredSheets": 0,
    "firstUnmarkedQuestion": 1,
  }]
}
```

`answeredSheets` is the number of sheets the students answered, or answered for a given question.

`firstUnmarkedQuestion` is the id of the first sheet not answer by a given student, or for a given question.

**Comment by barais** [comment]
I will do it now

**Comment by barais** [comment]
Not sure to understand the 
firstSheetNotAnswered (you mean the question ?)

**Comment by arnobl** [comment]
First student copy for which this question is not marked.
I change the name of the attribute
