### ISSUE TITLE
Backend crashes while annotating an exam template

### ISSUE THREAD

**Issue by arnobl** [correctexam/corrigeExamBack#66]
1. Create a new exam
2. Go to annotate it
3. create name, id, multiple question boxes
4. delete all of them
5. repeat operation 3 and 4 until an error 500 appears in the console. Then nothing can be done on the exam anymore

I suspect the front asking the back for removing a zone that does not exist anymore and the back crashes (error 500) instead of ignoring the request.

**Comment by arnobl** [comment]
I can reproduce the crash locally:
`Caused by: javax.persistence.EntityNotFoundException: Unable to find fr.istic.domain.Zone with id 5794` in the back console.
This happens when the front asks for a previously removed zone.
I will fix the front for not asking that, but the back should not crash.

**Comment by barais** [comment]
Ok, real bug, I will fix it soon
